In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

<h1>Load dataset</h1>

In [2]:
df = pd.read_csv("dataset/netflix_users.csv")

<h1>Explore dataset</h1>

<h3>Basic Inspection</h3>

In [3]:
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [4]:
df.shape

(25000, 8)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  str
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  str
 4   Subscription_Type  25000 non-null  str
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  str
 7   Last_Login         25000 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.5 MB

In [6]:
df.isnull().sum()

User_ID              0
Name                 0
Age                  0
Country              0
Subscription_Type    0
Watch_Time_Hours     0
Favorite_Genre       0
Last_Login           0
dtype: int64

In [7]:
df.describe()

            User_ID           Age  Watch_Time_Hours
count  25000.000000  25000.000000      25000.000000
mean   12500.500000     46.482880        500.468858
std     7217.022701     19.594861        286.381815
min        1.000000     13.000000          0.120000
25%     6250.750000     29.000000        256.567500
50%    12500.500000     46.000000        501.505000
75%    18750.250000     63.000000        745.732500
max    25000.000000     80.000000        999.990000

In [8]:
df.describe(include="all")

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
count,25000.000000,25000,25000.000000,25000,25000,25000.000000,25000,25000
unique,NaN,100,NaN,10,3,NaN,7,366
top,NaN,Michael Hernandez,NaN,UK,Premium,NaN,Horror,2024-09-05
freq,NaN,292,NaN,2592,8402,NaN,3654,92
mean,12500.500000,NaN,46.482880,NaN,NaN,500.468858,NaN,NaN
std,7217.022701,NaN,19.594861,NaN,NaN,286.381815,NaN,NaN
min,1.000000,NaN,13.000000,NaN,NaN,0.120000,NaN,NaN
25%,6250.750000,NaN,29.000000,NaN,NaN,256.567500,NaN,NaN
50%,12500.500000,NaN,46.000000,NaN,NaN,501.505000,NaN,NaN
75%,18750.250000,NaN,63.000000,NaN,NaN,745.732500,NaN,NaN
max,25000.000000,NaN,80.000000,NaN,NaN,999.990000,NaN,NaN

In [9]:
df.duplicated().sum()

np.int64(0)

<h3>Understanding categorical columns</h3>

In [10]:
df['Subscription_Type'].unique()

<StringArray>
['Premium', 'Basic', 'Standard']
Length: 3, dtype: str

In [12]:
df['Country'].unique()

<StringArray>
[   'France',       'USA',        'UK',    'Canada',    'Mexico',     'Japan',
 'Australia',   'Germany',    'Brazil',     'India']
Length: 10, dtype: str

In [13]:
df['Favorite_Genre'].unique()

<StringArray>
['Drama', 'Sci-Fi', 'Comedy', 'Documentary', 'Romance', 'Action', 'Horror']
Length: 7, dtype: str

In [14]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     8402
Basic       8356
Standard    8242
Name: count, dtype: int64

In [15]:
df['Country'].value_counts()

Country
UK           2592
Germany      2547
India        2505
USA          2503
Brazil       2503
Mexico       2493
Canada       2490
France       2473
Japan        2457
Australia    2437
Name: count, dtype: int64

In [16]:
df['Favorite_Genre'].value_counts()

Favorite_Genre
Horror         3654
Documentary    3636
Action         3589
Romance        3572
Comedy         3561
Drama          3533
Sci-Fi         3455
Name: count, dtype: int64

<h3>Convert Date Column</h3>

In [17]:
df['Last_Login'].dtype

In [18]:
df['Last_Login'] = pd.to_datetime(df['Last_Login'])

In [19]:
df['Last_Login'].dtype

dtype('<M8[us]')

<h4>Get Reference Date</h4>

In [22]:
df['Last_Login'].max()

Timestamp('2025-03-08 00:00:00')